[2022-05-18 22:34:42,265] {processor.py:163} INFO - Started process (PID=57) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:34:42,268] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:34:42,272] {logging_mixin.py:109} INFO - [2022-05-18 22:34:42,272] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:34:51,746] {logging_mixin.py:109} INFO - [2022-05-18 22:34:51,715] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:34:51,748] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:34:51,871] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 9.611 seconds
[2022-05-18 22:35:22,658] {processor.py:163} INFO - Started process (PID=93) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:35:22,660] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:35:22,661] {logging_mixin.py:109} INFO - [2022-05-18 22:35:22,661] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:35:23,985] {logging_mixin.py:109} INFO - [2022-05-18 22:35:23,949] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:35:23,986] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:35:24,010] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.359 seconds
[2022-05-18 22:35:55,017] {processor.py:163} INFO - Started process (PID=117) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:35:55,019] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:35:55,020] {logging_mixin.py:109} INFO - [2022-05-18 22:35:55,020] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:35:56,217] {logging_mixin.py:109} INFO - [2022-05-18 22:35:56,187] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:35:56,218] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:35:56,255] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.241 seconds
[2022-05-18 22:36:26,453] {processor.py:163} INFO - Started process (PID=145) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:36:26,455] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:36:26,457] {logging_mixin.py:109} INFO - [2022-05-18 22:36:26,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:36:27,768] {logging_mixin.py:109} INFO - [2022-05-18 22:36:27,741] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:36:27,769] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:36:27,838] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.392 seconds
[2022-05-18 22:36:58,081] {processor.py:163} INFO - Started process (PID=183) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:36:58,087] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:36:58,089] {logging_mixin.py:109} INFO - [2022-05-18 22:36:58,089] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:36:59,203] {logging_mixin.py:109} INFO - [2022-05-18 22:36:59,180] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:36:59,204] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:36:59,226] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.153 seconds
[2022-05-18 22:37:29,291] {processor.py:163} INFO - Started process (PID=207) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:37:29,294] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:37:29,296] {logging_mixin.py:109} INFO - [2022-05-18 22:37:29,296] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:37:30,504] {logging_mixin.py:109} INFO - [2022-05-18 22:37:30,478] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:37:30,505] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:37:30,528] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.242 seconds
[2022-05-18 22:38:00,642] {processor.py:163} INFO - Started process (PID=242) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:38:00,645] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:38:00,646] {logging_mixin.py:109} INFO - [2022-05-18 22:38:00,646] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:38:01,885] {logging_mixin.py:109} INFO - [2022-05-18 22:38:01,853] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:38:01,886] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:38:01,917] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.283 seconds
[2022-05-18 22:38:32,130] {processor.py:163} INFO - Started process (PID=270) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:38:32,132] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:38:32,134] {logging_mixin.py:109} INFO - [2022-05-18 22:38:32,134] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:38:33,417] {logging_mixin.py:109} INFO - [2022-05-18 22:38:33,391] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:38:33,418] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:38:33,447] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.322 seconds
[2022-05-18 22:39:03,641] {processor.py:163} INFO - Started process (PID=295) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:39:03,654] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:39:03,656] {logging_mixin.py:109} INFO - [2022-05-18 22:39:03,656] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:39:05,050] {logging_mixin.py:109} INFO - [2022-05-18 22:39:05,022] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:39:05,051] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:39:05,073] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.436 seconds
[2022-05-18 22:39:35,364] {processor.py:163} INFO - Started process (PID=329) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:39:35,367] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:39:35,369] {logging_mixin.py:109} INFO - [2022-05-18 22:39:35,369] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:39:36,624] {logging_mixin.py:109} INFO - [2022-05-18 22:39:36,598] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:39:36,625] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:39:36,651] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.295 seconds
[2022-05-18 22:40:06,780] {processor.py:163} INFO - Started process (PID=354) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:40:06,784] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:40:06,791] {logging_mixin.py:109} INFO - [2022-05-18 22:40:06,791] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:40:08,069] {logging_mixin.py:109} INFO - [2022-05-18 22:40:08,044] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:40:08,070] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:40:08,100] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.325 seconds
[2022-05-18 22:40:38,421] {processor.py:163} INFO - Started process (PID=388) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:40:38,424] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:40:38,425] {logging_mixin.py:109} INFO - [2022-05-18 22:40:38,425] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:40:39,595] {logging_mixin.py:109} INFO - [2022-05-18 22:40:39,570] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:40:39,596] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:40:39,618] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.205 seconds
[2022-05-18 22:41:09,772] {processor.py:163} INFO - Started process (PID=413) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:41:09,774] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:41:09,775] {logging_mixin.py:109} INFO - [2022-05-18 22:41:09,775] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:41:10,888] {logging_mixin.py:109} INFO - [2022-05-18 22:41:10,840] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:41:10,889] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:41:10,912] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.143 seconds
[2022-05-18 22:41:41,078] {processor.py:163} INFO - Started process (PID=452) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:41:41,080] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:41:41,083] {logging_mixin.py:109} INFO - [2022-05-18 22:41:41,083] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:41:42,780] {logging_mixin.py:109} INFO - [2022-05-18 22:41:42,736] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:41:42,782] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:41:42,850] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.779 seconds
[2022-05-18 22:42:13,219] {processor.py:163} INFO - Started process (PID=479) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:42:13,221] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:42:13,223] {logging_mixin.py:109} INFO - [2022-05-18 22:42:13,223] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:42:14,793] {logging_mixin.py:109} INFO - [2022-05-18 22:42:14,766] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:42:14,795] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:42:14,820] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.606 seconds
[2022-05-18 22:42:45,231] {processor.py:163} INFO - Started process (PID=518) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:42:45,248] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:42:45,251] {logging_mixin.py:109} INFO - [2022-05-18 22:42:45,250] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:42:47,000] {logging_mixin.py:109} INFO - [2022-05-18 22:42:46,974] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:42:47,002] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:42:47,027] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.814 seconds
[2022-05-18 22:43:17,264] {processor.py:163} INFO - Started process (PID=543) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:43:17,267] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:43:17,273] {logging_mixin.py:109} INFO - [2022-05-18 22:43:17,270] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:43:18,820] {logging_mixin.py:109} INFO - [2022-05-18 22:43:18,794] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:43:18,821] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:43:18,854] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.607 seconds
[2022-05-18 22:43:49,325] {processor.py:163} INFO - Started process (PID=568) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:43:49,327] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:43:49,328] {logging_mixin.py:109} INFO - [2022-05-18 22:43:49,328] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:43:50,796] {logging_mixin.py:109} INFO - [2022-05-18 22:43:50,746] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:43:50,797] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:43:50,852] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.535 seconds
[2022-05-18 22:44:22,198] {processor.py:163} INFO - Started process (PID=602) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:44:22,200] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:44:22,222] {logging_mixin.py:109} INFO - [2022-05-18 22:44:22,222] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:44:24,684] {logging_mixin.py:109} INFO - [2022-05-18 22:44:24,659] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:44:24,690] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:44:24,714] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.520 seconds
[2022-05-18 22:44:55,629] {processor.py:163} INFO - Started process (PID=629) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:44:55,648] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:44:55,665] {logging_mixin.py:109} INFO - [2022-05-18 22:44:55,665] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:44:57,408] {logging_mixin.py:109} INFO - [2022-05-18 22:44:57,380] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:44:57,409] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:44:57,434] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.810 seconds
[2022-05-18 22:45:27,574] {processor.py:163} INFO - Started process (PID=653) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:45:27,576] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:45:27,577] {logging_mixin.py:109} INFO - [2022-05-18 22:45:27,576] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:45:29,764] {logging_mixin.py:109} INFO - [2022-05-18 22:45:29,709] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 41, in <module>
    sql=insert_query_city(csv_path = "dimension_city")
  File "/opt/airflow/dags/utils/insert_queries.py", line 8, in insert_query_city
    dataframe =cargar_datos(kwargs['csv_path'])
  File "/opt/airflow/dags/utils/file_util.py", line 4, in cargar_datos
    df = pd.read_csv("/opt/airflow/data/" + name + ".csv", sep=',', encoding = 'utf-8', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/dimension_city.csv'
[2022-05-18 22:45:29,767] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:45:29,801] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.231 seconds
[2022-05-18 22:47:27,010] {processor.py:163} INFO - Started process (PID=56) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:47:27,026] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:47:27,028] {logging_mixin.py:109} INFO - [2022-05-18 22:47:27,028] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:47:31,238] {logging_mixin.py:109} INFO - [2022-05-18 22:47:31,206] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 69, in <module>
    sql=insert_query_stock(csv_path = "dimension_stock_item")
  File "/opt/airflow/dags/utils/insert_queries.py", line 52, in insert_query_stock
    insertQuery += insert + f"({row.Stock_Item_Key},\'{row.WWI_Stock_Item_ID}\',\'{row.Stock_Item}\',\'{row.Color}\',\'{row.Selling_Package}\',\'{row.Buying_Package}\',\'{row.Brand},\'{row.Size_val},\'{row.Lead_Time_Days},\'{row.Quantity_Per_Outer},\'{row.Is_Chiller_Stock},\'{row.Tax_Rate},\'{row.Unit_Price},\'{row.Recommended_Retail_Price},\'{row.Typical_Weight_Per_Unit});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'WWI_Stock_Item_ID'
[2022-05-18 22:47:31,248] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:47:31,326] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 4.319 seconds
[2022-05-18 22:48:01,585] {processor.py:163} INFO - Started process (PID=80) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:48:01,588] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:48:01,590] {logging_mixin.py:109} INFO - [2022-05-18 22:48:01,589] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:48:03,257] {logging_mixin.py:109} INFO - [2022-05-18 22:48:03,241] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 69, in <module>
    sql=insert_query_stock(csv_path = "dimension_stock_item")
  File "/opt/airflow/dags/utils/insert_queries.py", line 52, in insert_query_stock
    insertQuery += insert + f"({row.Stock_Item_Key},\'{row.WWI_Stock_Item_ID}\',\'{row.Stock_Item}\',\'{row.Color}\',\'{row.Selling_Package}\',\'{row.Buying_Package}\',\'{row.Brand},\'{row.Size_val},\'{row.Lead_Time_Days},\'{row.Quantity_Per_Outer},\'{row.Is_Chiller_Stock},\'{row.Tax_Rate},\'{row.Unit_Price},\'{row.Recommended_Retail_Price},\'{row.Typical_Weight_Per_Unit});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'WWI_Stock_Item_ID'
[2022-05-18 22:48:03,260] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:48:03,283] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.704 seconds
[2022-05-18 22:48:33,582] {processor.py:163} INFO - Started process (PID=107) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:48:33,584] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:48:33,585] {logging_mixin.py:109} INFO - [2022-05-18 22:48:33,585] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:48:35,456] {logging_mixin.py:109} INFO - [2022-05-18 22:48:35,435] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 69, in <module>
    sql=insert_query_stock(csv_path = "dimension_stock_item")
  File "/opt/airflow/dags/utils/insert_queries.py", line 52, in insert_query_stock
    insertQuery += insert + f"({row.Stock_Item_Key},\'{row.WWI_Stock_Item_ID}\',\'{row.Stock_Item}\',\'{row.Color}\',\'{row.Selling_Package}\',\'{row.Buying_Package}\',\'{row.Brand},\'{row.Size_val},\'{row.Lead_Time_Days},\'{row.Quantity_Per_Outer},\'{row.Is_Chiller_Stock},\'{row.Tax_Rate},\'{row.Unit_Price},\'{row.Recommended_Retail_Price},\'{row.Typical_Weight_Per_Unit});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'WWI_Stock_Item_ID'
[2022-05-18 22:48:35,460] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:48:35,491] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.913 seconds
[2022-05-18 22:49:05,675] {processor.py:163} INFO - Started process (PID=145) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:49:05,678] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:49:05,680] {logging_mixin.py:109} INFO - [2022-05-18 22:49:05,680] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:49:07,373] {logging_mixin.py:109} INFO - [2022-05-18 22:49:07,350] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 69, in <module>
    sql=insert_query_stock(csv_path = "dimension_stock_item")
  File "/opt/airflow/dags/utils/insert_queries.py", line 52, in insert_query_stock
    insertQuery += insert + f"({row.Stock_Item_Key},\'{row.WWI_Stock_Item_ID}\',\'{row.Stock_Item}\',\'{row.Color}\',\'{row.Selling_Package}\',\'{row.Buying_Package}\',\'{row.Brand},\'{row.Size_val},\'{row.Lead_Time_Days},\'{row.Quantity_Per_Outer},\'{row.Is_Chiller_Stock},\'{row.Tax_Rate},\'{row.Unit_Price},\'{row.Recommended_Retail_Price},\'{row.Typical_Weight_Per_Unit});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'WWI_Stock_Item_ID'
[2022-05-18 22:49:07,377] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:49:07,403] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.734 seconds
[2022-05-18 22:49:37,524] {processor.py:163} INFO - Started process (PID=172) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:49:37,533] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:49:37,535] {logging_mixin.py:109} INFO - [2022-05-18 22:49:37,534] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:49:39,079] {logging_mixin.py:109} INFO - [2022-05-18 22:49:39,060] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 69, in <module>
    sql=insert_query_stock(csv_path = "dimension_stock_item")
  File "/opt/airflow/dags/utils/insert_queries.py", line 52, in insert_query_stock
    insertQuery += insert + f"({row.Stock_Item_Key},\'{row.WWI_Stock_Item_ID}\',\'{row.Stock_Item}\',\'{row.Color}\',\'{row.Selling_Package}\',\'{row.Buying_Package}\',\'{row.Brand},\'{row.Size_val},\'{row.Lead_Time_Days},\'{row.Quantity_Per_Outer},\'{row.Is_Chiller_Stock},\'{row.Tax_Rate},\'{row.Unit_Price},\'{row.Recommended_Retail_Price},\'{row.Typical_Weight_Per_Unit});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'WWI_Stock_Item_ID'
[2022-05-18 22:49:39,083] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:49:39,108] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.597 seconds
[2022-05-18 22:50:09,635] {processor.py:163} INFO - Started process (PID=209) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:50:09,637] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:50:09,638] {logging_mixin.py:109} INFO - [2022-05-18 22:50:09,638] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:50:11,099] {logging_mixin.py:109} INFO - [2022-05-18 22:50:11,080] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 69, in <module>
    sql=insert_query_stock(csv_path = "dimension_stock_item")
  File "/opt/airflow/dags/utils/insert_queries.py", line 52, in insert_query_stock
    insertQuery += insert + f"({row.Stock_Item_Key},\'{row.WWI_Stock_Item_ID}\',\'{row.Stock_Item}\',\'{row.Color}\',\'{row.Selling_Package}\',\'{row.Buying_Package}\',\'{row.Brand},\'{row.Size_val},\'{row.Lead_Time_Days},\'{row.Quantity_Per_Outer},\'{row.Is_Chiller_Stock},\'{row.Tax_Rate},\'{row.Unit_Price},\'{row.Recommended_Retail_Price},\'{row.Typical_Weight_Per_Unit});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'WWI_Stock_Item_ID'
[2022-05-18 22:50:11,103] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:50:11,128] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.498 seconds
[2022-05-18 22:52:25,783] {processor.py:163} INFO - Started process (PID=61) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:52:25,792] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:52:25,794] {logging_mixin.py:109} INFO - [2022-05-18 22:52:25,794] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:52:28,230] {logging_mixin.py:109} INFO - [2022-05-18 22:52:28,207] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.Order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'Order_Key'
[2022-05-18 22:52:28,235] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:52:28,266] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.490 seconds
[2022-05-18 22:52:58,682] {processor.py:163} INFO - Started process (PID=86) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:52:58,684] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:52:58,685] {logging_mixin.py:109} INFO - [2022-05-18 22:52:58,685] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:53:00,812] {logging_mixin.py:109} INFO - [2022-05-18 22:53:00,783] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.Order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'Order_Key'
[2022-05-18 22:53:00,828] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:53:00,857] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.179 seconds
[2022-05-18 22:53:30,972] {processor.py:163} INFO - Started process (PID=120) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:53:30,974] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:53:30,976] {logging_mixin.py:109} INFO - [2022-05-18 22:53:30,975] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:53:32,696] {logging_mixin.py:109} INFO - [2022-05-18 22:53:32,675] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.Order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'Order_Key'
[2022-05-18 22:53:32,700] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:53:32,725] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.758 seconds
[2022-05-18 22:56:42,074] {processor.py:163} INFO - Started process (PID=58) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:56:42,077] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:56:42,093] {logging_mixin.py:109} INFO - [2022-05-18 22:56:42,093] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:56:45,306] {logging_mixin.py:109} INFO - [2022-05-18 22:56:45,281] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'order_Key'
[2022-05-18 22:56:45,311] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:56:45,345] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.253 seconds
[2022-05-18 22:57:15,512] {processor.py:163} INFO - Started process (PID=82) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:57:15,513] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:57:15,515] {logging_mixin.py:109} INFO - [2022-05-18 22:57:15,515] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:57:17,705] {logging_mixin.py:109} INFO - [2022-05-18 22:57:17,665] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'order_Key'
[2022-05-18 22:57:17,713] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:57:17,769] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.262 seconds
[2022-05-18 22:57:47,956] {processor.py:163} INFO - Started process (PID=115) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:57:47,958] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:57:47,960] {logging_mixin.py:109} INFO - [2022-05-18 22:57:47,960] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:57:49,682] {logging_mixin.py:109} INFO - [2022-05-18 22:57:49,665] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'order_Key'
[2022-05-18 22:57:49,686] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:57:49,714] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.762 seconds
[2022-05-18 22:58:19,943] {processor.py:163} INFO - Started process (PID=141) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:58:19,944] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:58:19,945] {logging_mixin.py:109} INFO - [2022-05-18 22:58:19,945] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:58:21,718] {logging_mixin.py:109} INFO - [2022-05-18 22:58:21,701] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'order_Key'
[2022-05-18 22:58:21,722] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:58:21,748] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.809 seconds
[2022-05-18 22:58:51,949] {processor.py:163} INFO - Started process (PID=180) to work on /opt/airflow/dags/ELT.py
[2022-05-18 22:58:51,954] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 22:58:51,956] {logging_mixin.py:109} INFO - [2022-05-18 22:58:51,956] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 22:58:54,367] {logging_mixin.py:109} INFO - [2022-05-18 22:58:54,349] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_Key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'order_Key'
[2022-05-18 22:58:54,371] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 22:58:54,396] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.453 seconds
[2022-05-18 23:00:53,820] {processor.py:163} INFO - Started process (PID=57) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:00:53,850] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:00:53,857] {logging_mixin.py:109} INFO - [2022-05-18 23:00:53,856] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:00:56,840] {logging_mixin.py:109} INFO - [2022-05-18 23:00:56,816] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:00:56,844] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:00:56,888] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.083 seconds
[2022-05-18 23:01:27,235] {processor.py:163} INFO - Started process (PID=81) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:01:27,237] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:01:27,238] {logging_mixin.py:109} INFO - [2022-05-18 23:01:27,238] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:01:29,502] {logging_mixin.py:109} INFO - [2022-05-18 23:01:29,427] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:01:29,514] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:01:29,562] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.344 seconds
[2022-05-18 23:01:59,733] {processor.py:163} INFO - Started process (PID=121) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:01:59,735] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:01:59,737] {logging_mixin.py:109} INFO - [2022-05-18 23:01:59,737] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:02:01,678] {logging_mixin.py:109} INFO - [2022-05-18 23:02:01,658] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:02:01,682] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:02:01,707] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.979 seconds
[2022-05-18 23:02:31,949] {processor.py:163} INFO - Started process (PID=148) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:02:31,951] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:02:31,952] {logging_mixin.py:109} INFO - [2022-05-18 23:02:31,952] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:02:33,816] {logging_mixin.py:109} INFO - [2022-05-18 23:02:33,800] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:02:33,819] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:02:33,847] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.902 seconds
[2022-05-18 23:03:04,111] {processor.py:163} INFO - Started process (PID=184) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:03:04,113] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:03:04,114] {logging_mixin.py:109} INFO - [2022-05-18 23:03:04,114] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:03:05,883] {logging_mixin.py:109} INFO - [2022-05-18 23:03:05,862] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:03:05,888] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:03:05,928] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.821 seconds
[2022-05-18 23:03:36,137] {processor.py:163} INFO - Started process (PID=208) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:03:36,139] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:03:36,147] {logging_mixin.py:109} INFO - [2022-05-18 23:03:36,147] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:03:37,989] {logging_mixin.py:109} INFO - [2022-05-18 23:03:37,972] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:03:37,993] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:03:38,045] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.913 seconds
[2022-05-18 23:04:08,169] {processor.py:163} INFO - Started process (PID=243) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:04:08,171] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:04:08,172] {logging_mixin.py:109} INFO - [2022-05-18 23:04:08,172] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:04:12,105] {logging_mixin.py:109} INFO - [2022-05-18 23:04:12,040] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:04:12,112] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:04:12,141] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.986 seconds
[2022-05-18 23:04:42,460] {processor.py:163} INFO - Started process (PID=268) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:04:42,463] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:04:42,465] {logging_mixin.py:109} INFO - [2022-05-18 23:04:42,464] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:04:44,334] {logging_mixin.py:109} INFO - [2022-05-18 23:04:44,313] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:04:44,337] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:04:44,362] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.914 seconds
[2022-05-18 23:05:14,679] {processor.py:163} INFO - Started process (PID=292) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:05:14,682] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:05:14,683] {logging_mixin.py:109} INFO - [2022-05-18 23:05:14,683] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:05:17,216] {logging_mixin.py:109} INFO - [2022-05-18 23:05:17,155] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:05:17,221] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:05:17,253] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.581 seconds
[2022-05-18 23:05:47,582] {processor.py:163} INFO - Started process (PID=330) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:05:47,584] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:05:47,585] {logging_mixin.py:109} INFO - [2022-05-18 23:05:47,585] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:05:49,559] {logging_mixin.py:109} INFO - [2022-05-18 23:05:49,531] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:05:49,576] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:05:49,606] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.029 seconds
[2022-05-18 23:06:20,065] {processor.py:163} INFO - Started process (PID=355) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:06:20,072] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:06:20,077] {logging_mixin.py:109} INFO - [2022-05-18 23:06:20,077] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:06:22,041] {logging_mixin.py:109} INFO - [2022-05-18 23:06:22,022] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:06:22,049] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:06:22,080] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.023 seconds
[2022-05-18 23:06:52,414] {processor.py:163} INFO - Started process (PID=392) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:06:52,416] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:06:52,418] {logging_mixin.py:109} INFO - [2022-05-18 23:06:52,417] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:06:54,211] {logging_mixin.py:109} INFO - [2022-05-18 23:06:54,133] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT.py", line 77, in <module>
    sql=insert_query_fact_order(csv_path = "fact_order")
  File "/opt/airflow/dags/utils/insert_queries.py", line 63, in insert_query_fact_order
    insertQuery += insert + f"({row.order_key},\'{row.City_Key}\',\'{row.Customer_Key}\',\'{row.Stock_Item_Key}\',\'{row.Order_Date_Key}\',\'{row.Picked_Date_Key}\',\'{row.Salesperson_Key},\'{row.Picker_Key},\'{row.Package},\'{row.Quantity},\'{row.Unit_Price},\'{row.Tax_Rate},\'{row.Total_Excluding_Tax},\'{row.Tax_Amount},\'{row.Total_Including_Tax});\n"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'City_Key'
[2022-05-18 23:06:54,224] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:06:54,276] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.865 seconds
[2022-05-18 23:09:48,522] {processor.py:163} INFO - Started process (PID=52) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:09:48,524] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:09:48,526] {logging_mixin.py:109} INFO - [2022-05-18 23:09:48,525] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:09:52,517] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:10:02,495] {logging_mixin.py:109} INFO - [2022-05-18 23:10:02,494] {manager.py:496} INFO - Created Permission View: can read on DAG:ETL
[2022-05-18 23:10:02,518] {logging_mixin.py:109} INFO - [2022-05-18 23:10:02,518] {manager.py:496} INFO - Created Permission View: can edit on DAG:ETL
[2022-05-18 23:10:02,522] {logging_mixin.py:109} INFO - [2022-05-18 23:10:02,521] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:10:02,534] {logging_mixin.py:109} INFO - [2022-05-18 23:10:02,534] {dag.py:2417} INFO - Creating ORM DAG for ETL
[2022-05-18 23:10:02,632] {logging_mixin.py:109} INFO - [2022-05-18 23:10:02,632] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-17 00:00:00+00:00
[2022-05-18 23:10:02,653] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 14.139 seconds
[2022-05-18 23:10:33,211] {processor.py:163} INFO - Started process (PID=87) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:10:33,214] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:10:33,217] {logging_mixin.py:109} INFO - [2022-05-18 23:10:33,217] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:10:35,253] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:10:35,311] {logging_mixin.py:109} INFO - [2022-05-18 23:10:35,310] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:10:35,364] {logging_mixin.py:109} INFO - [2022-05-18 23:10:35,363] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-17 00:00:00+00:00
[2022-05-18 23:10:35,378] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.173 seconds
[2022-05-18 23:11:05,975] {processor.py:163} INFO - Started process (PID=126) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:11:06,002] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:11:06,005] {logging_mixin.py:109} INFO - [2022-05-18 23:11:06,005] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:11:17,276] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:11:17,318] {logging_mixin.py:109} INFO - [2022-05-18 23:11:17,318] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:11:17,341] {logging_mixin.py:109} INFO - [2022-05-18 23:11:17,341] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:11:17,357] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 11.457 seconds
[2022-05-18 23:11:47,576] {processor.py:163} INFO - Started process (PID=152) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:11:47,578] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:11:47,580] {logging_mixin.py:109} INFO - [2022-05-18 23:11:47,580] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:11:49,693] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:11:49,737] {logging_mixin.py:109} INFO - [2022-05-18 23:11:49,737] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:11:49,756] {logging_mixin.py:109} INFO - [2022-05-18 23:11:49,756] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:11:49,770] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.201 seconds
[2022-05-18 23:12:20,010] {processor.py:163} INFO - Started process (PID=187) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:12:20,012] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:12:20,013] {logging_mixin.py:109} INFO - [2022-05-18 23:12:20,013] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:12:22,257] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:12:22,301] {logging_mixin.py:109} INFO - [2022-05-18 23:12:22,301] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:12:22,322] {logging_mixin.py:109} INFO - [2022-05-18 23:12:22,322] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:12:22,336] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.331 seconds
[2022-05-18 23:12:52,595] {processor.py:163} INFO - Started process (PID=214) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:12:52,597] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:12:52,599] {logging_mixin.py:109} INFO - [2022-05-18 23:12:52,599] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:12:54,777] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:12:54,835] {logging_mixin.py:109} INFO - [2022-05-18 23:12:54,834] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:12:54,857] {logging_mixin.py:109} INFO - [2022-05-18 23:12:54,857] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:12:54,871] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.282 seconds
[2022-05-18 23:13:25,116] {processor.py:163} INFO - Started process (PID=249) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:13:25,119] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:13:25,122] {logging_mixin.py:109} INFO - [2022-05-18 23:13:25,122] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:13:28,022] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:13:28,073] {logging_mixin.py:109} INFO - [2022-05-18 23:13:28,073] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:13:28,092] {logging_mixin.py:109} INFO - [2022-05-18 23:13:28,092] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:13:28,114] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.009 seconds
[2022-05-18 23:13:58,700] {processor.py:163} INFO - Started process (PID=276) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:13:58,703] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:13:58,704] {logging_mixin.py:109} INFO - [2022-05-18 23:13:58,704] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:14:01,247] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:14:01,319] {logging_mixin.py:109} INFO - [2022-05-18 23:14:01,319] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:14:01,338] {logging_mixin.py:109} INFO - [2022-05-18 23:14:01,338] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:14:01,354] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.662 seconds
[2022-05-18 23:14:31,545] {processor.py:163} INFO - Started process (PID=312) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:14:31,547] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:14:31,548] {logging_mixin.py:109} INFO - [2022-05-18 23:14:31,548] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:14:33,683] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:14:33,715] {logging_mixin.py:109} INFO - [2022-05-18 23:14:33,715] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:14:33,736] {logging_mixin.py:109} INFO - [2022-05-18 23:14:33,735] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:14:33,750] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.210 seconds
[2022-05-18 23:15:04,034] {processor.py:163} INFO - Started process (PID=337) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:15:04,045] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:15:04,046] {logging_mixin.py:109} INFO - [2022-05-18 23:15:04,046] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:15:06,214] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:15:06,260] {logging_mixin.py:109} INFO - [2022-05-18 23:15:06,260] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:15:06,280] {logging_mixin.py:109} INFO - [2022-05-18 23:15:06,280] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:15:06,323] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.303 seconds
[2022-05-18 23:15:36,621] {processor.py:163} INFO - Started process (PID=373) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:15:36,623] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:15:36,625] {logging_mixin.py:109} INFO - [2022-05-18 23:15:36,625] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:15:38,729] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:15:38,786] {logging_mixin.py:109} INFO - [2022-05-18 23:15:38,785] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:15:38,812] {logging_mixin.py:109} INFO - [2022-05-18 23:15:38,811] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:15:38,826] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.210 seconds
[2022-05-18 23:16:09,046] {processor.py:163} INFO - Started process (PID=399) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:16:09,058] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:16:09,060] {logging_mixin.py:109} INFO - [2022-05-18 23:16:09,060] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:16:11,641] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:16:11,688] {logging_mixin.py:109} INFO - [2022-05-18 23:16:11,688] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:16:11,709] {logging_mixin.py:109} INFO - [2022-05-18 23:16:11,709] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:16:11,723] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.693 seconds
[2022-05-18 23:16:42,072] {processor.py:163} INFO - Started process (PID=435) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:16:42,077] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:16:42,090] {logging_mixin.py:109} INFO - [2022-05-18 23:16:42,090] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:16:44,637] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:16:44,670] {logging_mixin.py:109} INFO - [2022-05-18 23:16:44,670] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:16:44,688] {logging_mixin.py:109} INFO - [2022-05-18 23:16:44,688] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:16:44,704] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.648 seconds
[2022-05-18 23:17:14,949] {processor.py:163} INFO - Started process (PID=460) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:17:14,951] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:17:14,953] {logging_mixin.py:109} INFO - [2022-05-18 23:17:14,953] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:17:17,090] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:17:17,133] {logging_mixin.py:109} INFO - [2022-05-18 23:17:17,132] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:17:17,159] {logging_mixin.py:109} INFO - [2022-05-18 23:17:17,158] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:17:17,251] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.306 seconds
[2022-05-18 23:17:47,537] {processor.py:163} INFO - Started process (PID=496) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:17:47,546] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:17:47,548] {logging_mixin.py:109} INFO - [2022-05-18 23:17:47,547] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:17:51,140] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:17:51,203] {logging_mixin.py:109} INFO - [2022-05-18 23:17:51,203] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:17:51,222] {logging_mixin.py:109} INFO - [2022-05-18 23:17:51,222] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:17:51,241] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.709 seconds
[2022-05-18 23:18:21,718] {processor.py:163} INFO - Started process (PID=521) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:18:21,720] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:18:21,723] {logging_mixin.py:109} INFO - [2022-05-18 23:18:21,723] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:18:23,758] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:18:23,810] {logging_mixin.py:109} INFO - [2022-05-18 23:18:23,810] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:18:23,837] {logging_mixin.py:109} INFO - [2022-05-18 23:18:23,837] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:18:23,851] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.141 seconds
[2022-05-18 23:18:53,980] {processor.py:163} INFO - Started process (PID=557) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:18:53,996] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:18:53,998] {logging_mixin.py:109} INFO - [2022-05-18 23:18:53,998] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:18:55,993] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:18:56,029] {logging_mixin.py:109} INFO - [2022-05-18 23:18:56,028] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:18:56,050] {logging_mixin.py:109} INFO - [2022-05-18 23:18:56,050] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:18:56,064] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.088 seconds
[2022-05-18 23:19:26,490] {processor.py:163} INFO - Started process (PID=582) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:19:26,493] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:19:26,494] {logging_mixin.py:109} INFO - [2022-05-18 23:19:26,494] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:19:28,514] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:19:28,546] {logging_mixin.py:109} INFO - [2022-05-18 23:19:28,546] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:19:28,564] {logging_mixin.py:109} INFO - [2022-05-18 23:19:28,564] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:19:28,577] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.092 seconds
[2022-05-18 23:19:59,101] {processor.py:163} INFO - Started process (PID=607) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:19:59,103] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:19:59,104] {logging_mixin.py:109} INFO - [2022-05-18 23:19:59,104] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:20:02,149] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:20:02,187] {logging_mixin.py:109} INFO - [2022-05-18 23:20:02,186] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:20:02,204] {logging_mixin.py:109} INFO - [2022-05-18 23:20:02,204] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:20:02,218] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.123 seconds
[2022-05-18 23:20:32,460] {processor.py:163} INFO - Started process (PID=640) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:20:32,465] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:20:32,467] {logging_mixin.py:109} INFO - [2022-05-18 23:20:32,467] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:20:34,565] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:20:34,602] {logging_mixin.py:109} INFO - [2022-05-18 23:20:34,601] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:20:34,621] {logging_mixin.py:109} INFO - [2022-05-18 23:20:34,621] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:20:34,639] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.187 seconds
[2022-05-18 23:21:04,865] {processor.py:163} INFO - Started process (PID=674) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:21:04,866] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:21:04,868] {logging_mixin.py:109} INFO - [2022-05-18 23:21:04,868] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:21:06,903] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:21:06,940] {logging_mixin.py:109} INFO - [2022-05-18 23:21:06,940] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:21:06,963] {logging_mixin.py:109} INFO - [2022-05-18 23:21:06,963] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:21:06,984] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.125 seconds
[2022-05-18 23:21:37,398] {processor.py:163} INFO - Started process (PID=699) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:21:37,400] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:21:37,401] {logging_mixin.py:109} INFO - [2022-05-18 23:21:37,401] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:21:39,606] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:21:39,642] {logging_mixin.py:109} INFO - [2022-05-18 23:21:39,641] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:21:39,661] {logging_mixin.py:109} INFO - [2022-05-18 23:21:39,661] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:21:39,674] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.283 seconds
[2022-05-18 23:22:09,827] {processor.py:163} INFO - Started process (PID=735) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:22:09,828] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:22:09,830] {logging_mixin.py:109} INFO - [2022-05-18 23:22:09,830] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:22:12,453] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:22:12,486] {logging_mixin.py:109} INFO - [2022-05-18 23:22:12,486] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:22:12,503] {logging_mixin.py:109} INFO - [2022-05-18 23:22:12,503] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:22:12,515] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.693 seconds
[2022-05-18 23:22:42,841] {processor.py:163} INFO - Started process (PID=761) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:22:42,843] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:22:42,844] {logging_mixin.py:109} INFO - [2022-05-18 23:22:42,844] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:22:45,168] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:22:45,204] {logging_mixin.py:109} INFO - [2022-05-18 23:22:45,204] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:22:45,223] {logging_mixin.py:109} INFO - [2022-05-18 23:22:45,223] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:22:45,238] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.402 seconds
[2022-05-18 23:23:15,795] {processor.py:163} INFO - Started process (PID=798) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:23:15,815] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:23:15,820] {logging_mixin.py:109} INFO - [2022-05-18 23:23:15,820] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:23:17,987] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:23:18,021] {logging_mixin.py:109} INFO - [2022-05-18 23:23:18,020] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:23:18,038] {logging_mixin.py:109} INFO - [2022-05-18 23:23:18,038] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:23:18,051] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.270 seconds
[2022-05-18 23:23:48,370] {processor.py:163} INFO - Started process (PID=823) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:23:48,373] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:23:48,382] {logging_mixin.py:109} INFO - [2022-05-18 23:23:48,381] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:23:50,980] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:23:51,022] {logging_mixin.py:109} INFO - [2022-05-18 23:23:51,021] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:23:51,054] {logging_mixin.py:109} INFO - [2022-05-18 23:23:51,054] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:23:51,068] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.705 seconds
[2022-05-18 23:24:21,327] {processor.py:163} INFO - Started process (PID=848) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:24:21,330] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:24:21,331] {logging_mixin.py:109} INFO - [2022-05-18 23:24:21,331] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:24:23,570] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:24:23,621] {logging_mixin.py:109} INFO - [2022-05-18 23:24:23,620] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:24:23,671] {logging_mixin.py:109} INFO - [2022-05-18 23:24:23,671] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:24:23,690] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.368 seconds
[2022-05-18 23:24:54,055] {processor.py:163} INFO - Started process (PID=884) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:24:54,057] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:24:54,058] {logging_mixin.py:109} INFO - [2022-05-18 23:24:54,058] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:25:00,516] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:25:00,551] {logging_mixin.py:109} INFO - [2022-05-18 23:25:00,551] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:25:00,573] {logging_mixin.py:109} INFO - [2022-05-18 23:25:00,572] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:25:00,587] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 6.541 seconds
[2022-05-18 23:25:30,869] {processor.py:163} INFO - Started process (PID=909) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:25:30,882] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:25:30,886] {logging_mixin.py:109} INFO - [2022-05-18 23:25:30,886] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:25:33,030] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:25:33,067] {logging_mixin.py:109} INFO - [2022-05-18 23:25:33,066] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:25:33,091] {logging_mixin.py:109} INFO - [2022-05-18 23:25:33,091] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:25:33,108] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.243 seconds
[2022-05-18 23:26:03,380] {processor.py:163} INFO - Started process (PID=934) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:26:03,386] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:26:03,387] {logging_mixin.py:109} INFO - [2022-05-18 23:26:03,387] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:26:07,311] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:26:07,447] {logging_mixin.py:109} INFO - [2022-05-18 23:26:07,447] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:26:07,475] {logging_mixin.py:109} INFO - [2022-05-18 23:26:07,475] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:26:07,499] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 4.132 seconds
[2022-05-18 23:26:37,829] {processor.py:163} INFO - Started process (PID=970) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:26:37,831] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:26:37,833] {logging_mixin.py:109} INFO - [2022-05-18 23:26:37,832] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:26:40,072] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:26:40,113] {logging_mixin.py:109} INFO - [2022-05-18 23:26:40,112] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:26:40,133] {logging_mixin.py:109} INFO - [2022-05-18 23:26:40,132] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:26:40,148] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.324 seconds
[2022-05-18 23:27:10,366] {processor.py:163} INFO - Started process (PID=994) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:27:10,367] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:27:10,369] {logging_mixin.py:109} INFO - [2022-05-18 23:27:10,369] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:27:12,193] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:27:12,227] {logging_mixin.py:109} INFO - [2022-05-18 23:27:12,227] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:27:12,245] {logging_mixin.py:109} INFO - [2022-05-18 23:27:12,245] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:27:12,258] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.897 seconds
[2022-05-18 23:27:42,815] {processor.py:163} INFO - Started process (PID=1027) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:27:42,832] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:27:42,857] {logging_mixin.py:109} INFO - [2022-05-18 23:27:42,857] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:27:45,643] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:27:45,675] {logging_mixin.py:109} INFO - [2022-05-18 23:27:45,674] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:27:45,694] {logging_mixin.py:109} INFO - [2022-05-18 23:27:45,694] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:27:45,720] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.914 seconds
[2022-05-18 23:28:16,076] {processor.py:163} INFO - Started process (PID=1052) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:28:16,081] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:28:16,083] {logging_mixin.py:109} INFO - [2022-05-18 23:28:16,083] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:28:18,027] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:28:18,071] {logging_mixin.py:109} INFO - [2022-05-18 23:28:18,070] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:28:18,093] {logging_mixin.py:109} INFO - [2022-05-18 23:28:18,093] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:28:18,108] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.045 seconds
[2022-05-18 23:28:48,574] {processor.py:163} INFO - Started process (PID=1084) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:28:48,576] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:28:48,582] {logging_mixin.py:109} INFO - [2022-05-18 23:28:48,582] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:28:50,922] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:28:51,006] {logging_mixin.py:109} INFO - [2022-05-18 23:28:51,005] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:28:51,031] {logging_mixin.py:109} INFO - [2022-05-18 23:28:51,031] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:28:51,111] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.556 seconds
[2022-05-18 23:29:21,431] {processor.py:163} INFO - Started process (PID=1115) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:29:21,434] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:29:21,435] {logging_mixin.py:109} INFO - [2022-05-18 23:29:21,435] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:29:23,779] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:29:23,817] {logging_mixin.py:109} INFO - [2022-05-18 23:29:23,816] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:29:23,842] {logging_mixin.py:109} INFO - [2022-05-18 23:29:23,841] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:29:23,863] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.437 seconds
[2022-05-18 23:29:54,834] {processor.py:163} INFO - Started process (PID=1148) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:29:54,844] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:29:54,846] {logging_mixin.py:109} INFO - [2022-05-18 23:29:54,845] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:29:57,135] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:29:57,175] {logging_mixin.py:109} INFO - [2022-05-18 23:29:57,175] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:29:57,196] {logging_mixin.py:109} INFO - [2022-05-18 23:29:57,196] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:29:57,211] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.386 seconds
[2022-05-18 23:30:27,471] {processor.py:163} INFO - Started process (PID=1176) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:30:27,476] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:30:27,478] {logging_mixin.py:109} INFO - [2022-05-18 23:30:27,478] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:30:29,584] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:30:29,617] {logging_mixin.py:109} INFO - [2022-05-18 23:30:29,617] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:30:29,636] {logging_mixin.py:109} INFO - [2022-05-18 23:30:29,636] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:30:29,649] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.185 seconds
[2022-05-18 23:30:59,855] {processor.py:163} INFO - Started process (PID=1202) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:30:59,857] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:30:59,860] {logging_mixin.py:109} INFO - [2022-05-18 23:30:59,860] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:31:03,333] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:31:03,368] {logging_mixin.py:109} INFO - [2022-05-18 23:31:03,368] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:31:03,387] {logging_mixin.py:109} INFO - [2022-05-18 23:31:03,387] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:31:03,403] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.553 seconds
[2022-05-18 23:31:33,777] {processor.py:163} INFO - Started process (PID=1239) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:31:33,779] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:31:33,780] {logging_mixin.py:109} INFO - [2022-05-18 23:31:33,780] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:31:35,812] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:31:35,863] {logging_mixin.py:109} INFO - [2022-05-18 23:31:35,862] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:31:35,882] {logging_mixin.py:109} INFO - [2022-05-18 23:31:35,882] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:31:35,895] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.124 seconds
[2022-05-18 23:32:05,961] {processor.py:163} INFO - Started process (PID=1265) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:32:05,963] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:32:05,964] {logging_mixin.py:109} INFO - [2022-05-18 23:32:05,964] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:32:07,885] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:32:07,929] {logging_mixin.py:109} INFO - [2022-05-18 23:32:07,929] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:32:07,950] {logging_mixin.py:109} INFO - [2022-05-18 23:32:07,950] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:32:07,963] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.007 seconds
[2022-05-18 23:32:38,312] {processor.py:163} INFO - Started process (PID=1301) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:32:38,314] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:32:38,317] {logging_mixin.py:109} INFO - [2022-05-18 23:32:38,316] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:32:40,281] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:32:40,323] {logging_mixin.py:109} INFO - [2022-05-18 23:32:40,322] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:32:40,343] {logging_mixin.py:109} INFO - [2022-05-18 23:32:40,342] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:32:40,357] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.051 seconds
[2022-05-18 23:33:10,539] {processor.py:163} INFO - Started process (PID=1326) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:33:10,540] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:33:10,541] {logging_mixin.py:109} INFO - [2022-05-18 23:33:10,541] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:33:12,685] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:33:12,719] {logging_mixin.py:109} INFO - [2022-05-18 23:33:12,719] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:33:12,737] {logging_mixin.py:109} INFO - [2022-05-18 23:33:12,737] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:33:12,750] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.216 seconds
[2022-05-18 23:33:42,916] {processor.py:163} INFO - Started process (PID=1362) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:33:42,919] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:33:42,920] {logging_mixin.py:109} INFO - [2022-05-18 23:33:42,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:33:44,968] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:33:45,003] {logging_mixin.py:109} INFO - [2022-05-18 23:33:45,003] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:33:45,023] {logging_mixin.py:109} INFO - [2022-05-18 23:33:45,023] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:33:45,037] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.130 seconds
[2022-05-18 23:34:15,093] {processor.py:163} INFO - Started process (PID=1386) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:34:15,095] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:34:15,096] {logging_mixin.py:109} INFO - [2022-05-18 23:34:15,096] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:34:17,370] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:34:17,416] {logging_mixin.py:109} INFO - [2022-05-18 23:34:17,416] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:34:17,435] {logging_mixin.py:109} INFO - [2022-05-18 23:34:17,435] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:34:17,448] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.361 seconds
[2022-05-18 23:34:47,691] {processor.py:163} INFO - Started process (PID=1423) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:34:47,693] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:34:47,696] {logging_mixin.py:109} INFO - [2022-05-18 23:34:47,696] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:34:50,004] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:34:50,070] {logging_mixin.py:109} INFO - [2022-05-18 23:34:50,069] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:34:50,089] {logging_mixin.py:109} INFO - [2022-05-18 23:34:50,089] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:34:50,104] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.420 seconds
[2022-05-18 23:35:20,439] {processor.py:163} INFO - Started process (PID=1448) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:35:20,441] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:35:20,443] {logging_mixin.py:109} INFO - [2022-05-18 23:35:20,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:35:22,478] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:35:22,512] {logging_mixin.py:109} INFO - [2022-05-18 23:35:22,511] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:35:22,530] {logging_mixin.py:109} INFO - [2022-05-18 23:35:22,530] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:35:22,543] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.109 seconds
[2022-05-18 23:35:52,646] {processor.py:163} INFO - Started process (PID=1484) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:35:52,649] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:35:52,650] {logging_mixin.py:109} INFO - [2022-05-18 23:35:52,650] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:35:54,825] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:35:54,868] {logging_mixin.py:109} INFO - [2022-05-18 23:35:54,867] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:35:54,887] {logging_mixin.py:109} INFO - [2022-05-18 23:35:54,887] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:35:54,900] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.276 seconds
[2022-05-18 23:36:25,205] {processor.py:163} INFO - Started process (PID=1507) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:36:25,207] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:36:25,209] {logging_mixin.py:109} INFO - [2022-05-18 23:36:25,209] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:36:27,276] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:36:27,312] {logging_mixin.py:109} INFO - [2022-05-18 23:36:27,312] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:36:27,331] {logging_mixin.py:109} INFO - [2022-05-18 23:36:27,330] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:36:27,345] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.145 seconds
[2022-05-18 23:36:57,603] {processor.py:163} INFO - Started process (PID=1532) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:36:57,604] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:36:57,606] {logging_mixin.py:109} INFO - [2022-05-18 23:36:57,606] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:37:01,996] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:37:02,054] {logging_mixin.py:109} INFO - [2022-05-18 23:37:02,054] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:37:02,085] {logging_mixin.py:109} INFO - [2022-05-18 23:37:02,085] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:37:02,106] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 4.508 seconds
[2022-05-18 23:37:32,814] {processor.py:163} INFO - Started process (PID=1565) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:37:32,818] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:37:32,825] {logging_mixin.py:109} INFO - [2022-05-18 23:37:32,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:37:35,733] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:37:35,776] {logging_mixin.py:109} INFO - [2022-05-18 23:37:35,776] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:37:35,806] {logging_mixin.py:109} INFO - [2022-05-18 23:37:35,806] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:37:35,847] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.042 seconds
[2022-05-18 23:38:06,908] {processor.py:163} INFO - Started process (PID=1591) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:38:06,932] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:38:06,939] {logging_mixin.py:109} INFO - [2022-05-18 23:38:06,939] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:38:10,105] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:38:10,150] {logging_mixin.py:109} INFO - [2022-05-18 23:38:10,149] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:38:10,174] {logging_mixin.py:109} INFO - [2022-05-18 23:38:10,173] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:38:10,195] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.316 seconds
[2022-05-18 23:38:41,142] {processor.py:163} INFO - Started process (PID=1624) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:38:41,144] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:38:41,150] {logging_mixin.py:109} INFO - [2022-05-18 23:38:41,149] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:38:43,812] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:38:43,844] {logging_mixin.py:109} INFO - [2022-05-18 23:38:43,844] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:38:43,863] {logging_mixin.py:109} INFO - [2022-05-18 23:38:43,862] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:38:43,875] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.740 seconds
[2022-05-18 23:39:14,355] {processor.py:163} INFO - Started process (PID=1648) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:39:14,357] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:39:14,359] {logging_mixin.py:109} INFO - [2022-05-18 23:39:14,358] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:39:21,216] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:39:21,459] {logging_mixin.py:109} INFO - [2022-05-18 23:39:21,448] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:39:21,544] {logging_mixin.py:109} INFO - [2022-05-18 23:39:21,544] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:39:21,638] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 7.286 seconds
[2022-05-18 23:39:52,570] {processor.py:163} INFO - Started process (PID=1684) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:39:52,576] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:39:52,577] {logging_mixin.py:109} INFO - [2022-05-18 23:39:52,577] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:39:55,575] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:39:55,710] {logging_mixin.py:109} INFO - [2022-05-18 23:39:55,710] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:39:55,786] {logging_mixin.py:109} INFO - [2022-05-18 23:39:55,782] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:39:55,815] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.273 seconds
[2022-05-18 23:40:26,221] {processor.py:163} INFO - Started process (PID=1716) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:40:26,223] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:40:26,225] {logging_mixin.py:109} INFO - [2022-05-18 23:40:26,224] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:40:28,373] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:40:28,407] {logging_mixin.py:109} INFO - [2022-05-18 23:40:28,406] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:40:28,425] {logging_mixin.py:109} INFO - [2022-05-18 23:40:28,425] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:40:28,437] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.222 seconds
[2022-05-18 23:40:58,707] {processor.py:163} INFO - Started process (PID=1743) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:40:58,711] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:40:58,713] {logging_mixin.py:109} INFO - [2022-05-18 23:40:58,713] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:41:01,265] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:41:01,310] {logging_mixin.py:109} INFO - [2022-05-18 23:41:01,310] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:41:01,333] {logging_mixin.py:109} INFO - [2022-05-18 23:41:01,333] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:41:01,371] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.668 seconds
[2022-05-18 23:41:31,723] {processor.py:163} INFO - Started process (PID=1776) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:41:31,726] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:41:31,727] {logging_mixin.py:109} INFO - [2022-05-18 23:41:31,727] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:41:34,114] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:41:34,149] {logging_mixin.py:109} INFO - [2022-05-18 23:41:34,149] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:41:34,178] {logging_mixin.py:109} INFO - [2022-05-18 23:41:34,178] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:41:34,195] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.480 seconds
[2022-05-18 23:42:04,346] {processor.py:163} INFO - Started process (PID=1801) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:42:04,349] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:42:04,351] {logging_mixin.py:109} INFO - [2022-05-18 23:42:04,351] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:42:07,321] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:42:07,381] {logging_mixin.py:109} INFO - [2022-05-18 23:42:07,381] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:42:07,469] {logging_mixin.py:109} INFO - [2022-05-18 23:42:07,468] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:42:07,506] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.165 seconds
[2022-05-18 23:42:37,710] {processor.py:163} INFO - Started process (PID=1835) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:42:37,712] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:42:37,713] {logging_mixin.py:109} INFO - [2022-05-18 23:42:37,713] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:42:39,731] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:42:39,767] {logging_mixin.py:109} INFO - [2022-05-18 23:42:39,766] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:42:39,786] {logging_mixin.py:109} INFO - [2022-05-18 23:42:39,785] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:42:39,799] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.094 seconds
[2022-05-18 23:43:10,010] {processor.py:163} INFO - Started process (PID=1860) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:43:10,013] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:43:10,015] {logging_mixin.py:109} INFO - [2022-05-18 23:43:10,015] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:43:12,367] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:43:12,400] {logging_mixin.py:109} INFO - [2022-05-18 23:43:12,400] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:43:12,421] {logging_mixin.py:109} INFO - [2022-05-18 23:43:12,420] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:43:12,437] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.434 seconds
[2022-05-18 23:43:42,638] {processor.py:163} INFO - Started process (PID=1894) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:43:42,640] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:43:42,641] {logging_mixin.py:109} INFO - [2022-05-18 23:43:42,641] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:43:44,696] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:43:44,734] {logging_mixin.py:109} INFO - [2022-05-18 23:43:44,734] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:43:44,754] {logging_mixin.py:109} INFO - [2022-05-18 23:43:44,753] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:43:44,780] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.152 seconds
[2022-05-18 23:44:14,851] {processor.py:163} INFO - Started process (PID=1920) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:44:14,853] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:44:14,855] {logging_mixin.py:109} INFO - [2022-05-18 23:44:14,854] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:44:16,895] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:44:16,928] {logging_mixin.py:109} INFO - [2022-05-18 23:44:16,928] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:44:16,946] {logging_mixin.py:109} INFO - [2022-05-18 23:44:16,946] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:44:16,960] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.115 seconds
[2022-05-18 23:44:47,248] {processor.py:163} INFO - Started process (PID=1956) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:44:47,250] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:44:47,252] {logging_mixin.py:109} INFO - [2022-05-18 23:44:47,252] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:44:49,134] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:44:49,168] {logging_mixin.py:109} INFO - [2022-05-18 23:44:49,167] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:44:49,186] {logging_mixin.py:109} INFO - [2022-05-18 23:44:49,186] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:44:49,199] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.956 seconds
[2022-05-18 23:45:19,559] {processor.py:163} INFO - Started process (PID=1982) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:45:19,561] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:45:19,562] {logging_mixin.py:109} INFO - [2022-05-18 23:45:19,562] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:45:21,384] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:45:21,417] {logging_mixin.py:109} INFO - [2022-05-18 23:45:21,417] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:45:21,435] {logging_mixin.py:109} INFO - [2022-05-18 23:45:21,435] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:45:21,449] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.895 seconds
[2022-05-18 23:45:51,664] {processor.py:163} INFO - Started process (PID=2018) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:45:51,666] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:45:51,667] {logging_mixin.py:109} INFO - [2022-05-18 23:45:51,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:45:53,567] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:45:53,601] {logging_mixin.py:109} INFO - [2022-05-18 23:45:53,601] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:45:53,619] {logging_mixin.py:109} INFO - [2022-05-18 23:45:53,619] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:45:53,642] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.986 seconds
[2022-05-18 23:46:23,842] {processor.py:163} INFO - Started process (PID=2044) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:46:23,844] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:46:23,845] {logging_mixin.py:109} INFO - [2022-05-18 23:46:23,845] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:46:25,571] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:46:25,610] {logging_mixin.py:109} INFO - [2022-05-18 23:46:25,610] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:46:25,633] {logging_mixin.py:109} INFO - [2022-05-18 23:46:25,633] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:46:25,652] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.814 seconds
[2022-05-18 23:46:55,851] {processor.py:163} INFO - Started process (PID=2080) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:46:55,855] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:46:55,856] {logging_mixin.py:109} INFO - [2022-05-18 23:46:55,856] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:46:58,287] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:46:58,353] {logging_mixin.py:109} INFO - [2022-05-18 23:46:58,352] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:46:58,381] {logging_mixin.py:109} INFO - [2022-05-18 23:46:58,381] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:46:58,399] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.554 seconds
[2022-05-18 23:47:28,625] {processor.py:163} INFO - Started process (PID=2105) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:47:28,628] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:47:28,630] {logging_mixin.py:109} INFO - [2022-05-18 23:47:28,629] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:47:31,196] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:47:31,247] {logging_mixin.py:109} INFO - [2022-05-18 23:47:31,247] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:47:31,270] {logging_mixin.py:109} INFO - [2022-05-18 23:47:31,270] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:47:31,285] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.669 seconds
[2022-05-18 23:48:01,605] {processor.py:163} INFO - Started process (PID=2145) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:48:01,607] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:48:01,609] {logging_mixin.py:109} INFO - [2022-05-18 23:48:01,608] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:48:03,648] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:48:03,681] {logging_mixin.py:109} INFO - [2022-05-18 23:48:03,681] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:48:03,699] {logging_mixin.py:109} INFO - [2022-05-18 23:48:03,699] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:48:03,712] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.114 seconds
[2022-05-18 23:48:33,969] {processor.py:163} INFO - Started process (PID=2171) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:48:33,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:48:33,973] {logging_mixin.py:109} INFO - [2022-05-18 23:48:33,973] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:48:36,047] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:48:36,093] {logging_mixin.py:109} INFO - [2022-05-18 23:48:36,093] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:48:36,115] {logging_mixin.py:109} INFO - [2022-05-18 23:48:36,115] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:48:36,128] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.165 seconds
[2022-05-18 23:49:06,438] {processor.py:163} INFO - Started process (PID=2205) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:49:06,443] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:49:06,444] {logging_mixin.py:109} INFO - [2022-05-18 23:49:06,444] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:49:08,646] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:49:08,689] {logging_mixin.py:109} INFO - [2022-05-18 23:49:08,688] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:49:08,710] {logging_mixin.py:109} INFO - [2022-05-18 23:49:08,709] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:49:08,728] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.296 seconds
[2022-05-18 23:49:38,933] {processor.py:163} INFO - Started process (PID=2230) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:49:38,936] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:49:38,938] {logging_mixin.py:109} INFO - [2022-05-18 23:49:38,938] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:49:41,136] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:49:41,175] {logging_mixin.py:109} INFO - [2022-05-18 23:49:41,174] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:49:41,193] {logging_mixin.py:109} INFO - [2022-05-18 23:49:41,193] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:49:41,207] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.281 seconds
[2022-05-18 23:50:11,598] {processor.py:163} INFO - Started process (PID=2269) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:50:11,601] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:50:11,602] {logging_mixin.py:109} INFO - [2022-05-18 23:50:11,602] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:50:13,705] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:50:13,741] {logging_mixin.py:109} INFO - [2022-05-18 23:50:13,741] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:50:13,762] {logging_mixin.py:109} INFO - [2022-05-18 23:50:13,762] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:50:13,785] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.194 seconds
[2022-05-18 23:50:43,909] {processor.py:163} INFO - Started process (PID=2298) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:50:43,911] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:50:43,914] {logging_mixin.py:109} INFO - [2022-05-18 23:50:43,913] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:50:45,821] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:50:45,861] {logging_mixin.py:109} INFO - [2022-05-18 23:50:45,861] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:50:45,879] {logging_mixin.py:109} INFO - [2022-05-18 23:50:45,879] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:50:45,893] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.992 seconds
[2022-05-18 23:51:16,153] {processor.py:163} INFO - Started process (PID=2333) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:51:16,163] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:51:16,166] {logging_mixin.py:109} INFO - [2022-05-18 23:51:16,166] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:51:18,398] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:51:18,433] {logging_mixin.py:109} INFO - [2022-05-18 23:51:18,432] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:51:18,451] {logging_mixin.py:109} INFO - [2022-05-18 23:51:18,451] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:51:18,465] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.321 seconds
[2022-05-18 23:51:48,644] {processor.py:163} INFO - Started process (PID=2364) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:51:48,647] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:51:48,648] {logging_mixin.py:109} INFO - [2022-05-18 23:51:48,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:51:50,945] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:51:51,019] {logging_mixin.py:109} INFO - [2022-05-18 23:51:51,018] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:51:51,049] {logging_mixin.py:109} INFO - [2022-05-18 23:51:51,049] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:51:51,067] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.438 seconds
[2022-05-18 23:52:21,423] {processor.py:163} INFO - Started process (PID=2399) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:52:21,430] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:52:21,432] {logging_mixin.py:109} INFO - [2022-05-18 23:52:21,432] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:52:23,918] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:52:23,955] {logging_mixin.py:109} INFO - [2022-05-18 23:52:23,955] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:52:23,975] {logging_mixin.py:109} INFO - [2022-05-18 23:52:23,975] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:52:23,988] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.590 seconds
[2022-05-18 23:52:54,260] {processor.py:163} INFO - Started process (PID=2427) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:52:54,263] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:52:54,265] {logging_mixin.py:109} INFO - [2022-05-18 23:52:54,264] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:52:56,424] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:52:56,464] {logging_mixin.py:109} INFO - [2022-05-18 23:52:56,463] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:52:56,485] {logging_mixin.py:109} INFO - [2022-05-18 23:52:56,485] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:52:56,498] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.247 seconds
[2022-05-18 23:53:26,595] {processor.py:163} INFO - Started process (PID=2453) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:53:26,598] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:53:26,600] {logging_mixin.py:109} INFO - [2022-05-18 23:53:26,599] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:53:28,901] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:53:28,993] {logging_mixin.py:109} INFO - [2022-05-18 23:53:28,993] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:53:29,052] {logging_mixin.py:109} INFO - [2022-05-18 23:53:29,051] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:53:29,138] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.550 seconds
[2022-05-18 23:54:00,454] {processor.py:163} INFO - Started process (PID=2490) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:54:00,459] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:54:00,469] {logging_mixin.py:109} INFO - [2022-05-18 23:54:00,469] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:54:04,497] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:54:04,532] {logging_mixin.py:109} INFO - [2022-05-18 23:54:04,531] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:54:04,551] {logging_mixin.py:109} INFO - [2022-05-18 23:54:04,551] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:54:04,565] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 4.132 seconds
[2022-05-18 23:54:34,808] {processor.py:163} INFO - Started process (PID=2516) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:54:34,816] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:54:34,819] {logging_mixin.py:109} INFO - [2022-05-18 23:54:34,818] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:54:36,990] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:54:37,031] {logging_mixin.py:109} INFO - [2022-05-18 23:54:37,031] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:54:37,048] {logging_mixin.py:109} INFO - [2022-05-18 23:54:37,048] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:54:37,061] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.260 seconds
[2022-05-18 23:55:07,261] {processor.py:163} INFO - Started process (PID=2552) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:55:07,263] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:55:07,264] {logging_mixin.py:109} INFO - [2022-05-18 23:55:07,264] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:55:08,960] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:55:08,998] {logging_mixin.py:109} INFO - [2022-05-18 23:55:08,998] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:55:09,017] {logging_mixin.py:109} INFO - [2022-05-18 23:55:09,017] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:55:09,029] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.775 seconds
[2022-05-18 23:55:39,203] {processor.py:163} INFO - Started process (PID=2577) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:55:39,205] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:55:39,206] {logging_mixin.py:109} INFO - [2022-05-18 23:55:39,206] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:55:41,089] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:55:41,161] {logging_mixin.py:109} INFO - [2022-05-18 23:55:41,160] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:55:41,194] {logging_mixin.py:109} INFO - [2022-05-18 23:55:41,194] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:55:41,213] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.016 seconds
[2022-05-18 23:56:11,410] {processor.py:163} INFO - Started process (PID=2613) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:56:11,412] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:56:11,414] {logging_mixin.py:109} INFO - [2022-05-18 23:56:11,413] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:56:13,151] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:56:13,184] {logging_mixin.py:109} INFO - [2022-05-18 23:56:13,184] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:56:13,204] {logging_mixin.py:109} INFO - [2022-05-18 23:56:13,204] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:56:13,216] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.810 seconds
[2022-05-18 23:56:43,794] {processor.py:163} INFO - Started process (PID=2637) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:56:43,806] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:56:43,809] {logging_mixin.py:109} INFO - [2022-05-18 23:56:43,809] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:56:54,889] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:56:55,743] {logging_mixin.py:109} INFO - [2022-05-18 23:56:55,741] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:56:55,814] {logging_mixin.py:109} INFO - [2022-05-18 23:56:55,814] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:56:55,993] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 12.215 seconds
[2022-05-18 23:57:26,114] {processor.py:163} INFO - Started process (PID=2672) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:57:26,116] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:57:26,118] {logging_mixin.py:109} INFO - [2022-05-18 23:57:26,118] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:57:28,149] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:57:28,181] {logging_mixin.py:109} INFO - [2022-05-18 23:57:28,181] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:57:28,199] {logging_mixin.py:109} INFO - [2022-05-18 23:57:28,199] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:57:28,211] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.103 seconds
[2022-05-18 23:57:58,352] {processor.py:163} INFO - Started process (PID=2705) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:57:58,375] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:57:58,376] {logging_mixin.py:109} INFO - [2022-05-18 23:57:58,376] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:58:00,848] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:58:00,994] {logging_mixin.py:109} INFO - [2022-05-18 23:58:00,994] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:58:01,070] {logging_mixin.py:109} INFO - [2022-05-18 23:58:01,070] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:58:01,089] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 2.742 seconds
[2022-05-18 23:58:31,287] {processor.py:163} INFO - Started process (PID=2730) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:58:31,289] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:58:31,291] {logging_mixin.py:109} INFO - [2022-05-18 23:58:31,291] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:58:33,154] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:58:33,187] {logging_mixin.py:109} INFO - [2022-05-18 23:58:33,187] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:58:33,204] {logging_mixin.py:109} INFO - [2022-05-18 23:58:33,204] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:58:33,216] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.935 seconds
[2022-05-18 23:59:03,643] {processor.py:163} INFO - Started process (PID=2757) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:59:03,645] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:59:03,646] {logging_mixin.py:109} INFO - [2022-05-18 23:59:03,646] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:59:05,384] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:59:05,415] {logging_mixin.py:109} INFO - [2022-05-18 23:59:05,415] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:59:05,432] {logging_mixin.py:109} INFO - [2022-05-18 23:59:05,432] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:59:05,444] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 1.806 seconds
[2022-05-18 23:59:35,874] {processor.py:163} INFO - Started process (PID=2785) to work on /opt/airflow/dags/ELT.py
[2022-05-18 23:59:35,877] {processor.py:642} INFO - Processing file /opt/airflow/dags/ELT.py for tasks to queue
[2022-05-18 23:59:35,879] {logging_mixin.py:109} INFO - [2022-05-18 23:59:35,879] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/ELT.py
[2022-05-18 23:59:39,414] {processor.py:652} INFO - DAG(s) dict_keys(['ETL']) retrieved from /opt/airflow/dags/ELT.py
[2022-05-18 23:59:39,584] {logging_mixin.py:109} INFO - [2022-05-18 23:59:39,582] {dag.py:2398} INFO - Sync 1 DAGs
[2022-05-18 23:59:39,658] {logging_mixin.py:109} INFO - [2022-05-18 23:59:39,658] {dag.py:2937} INFO - Setting next_dagrun for ETL to 2022-05-18T00:00:00+00:00
[2022-05-18 23:59:39,745] {processor.py:171} INFO - Processing /opt/airflow/dags/ELT.py took 3.886 seconds
